services:
  epic_global_contracts:
      image: ghcr.io/${org}/epic-global-contracts:${EPIC_GLOBAL_CONTRACTS_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      environment:
        CONTRACT_SERVICE_BACKEND_BASE_URL: ${CONTRACT_SERVICE_BACKEND_BASE_URL:?CONTRACT_SERVICE_BACKEND_BASE_URL is not set}
        CONTRACT_SERVICE_AI_BASE_URL: ${CONTRACT_SERVICE_AI_BASE_URL:?CONTRACT_SERVICE_AI_BASE_URL is not set}
        CONTRACT_SERVICE_DATABASE_URI: ${CONTRACT_SERVICE_DATABASE_URI:?CONTRACT_SERVICE_DATABASE_URI is not set}
        CONTRACT_SERVICE_ENDPOINT: ${CONTRACT_SERVICE_ENDPOINT:?CONTRACT_SERVICE_ENDPOINT is not set}
        CONTRACT_SERVICE_ACCESS_KEY: ${CONTRACT_SERVICE_ACCESS_KEY:?CONTRACT_SERVICE_ACCESS_KEY is not set}
        CONTRACT_SERVICE_SECRET_KEY: ${CONTRACT_SERVICE_SECRET_KEY:?CONTRACT_SERVICE_SECRET_KEY is not set}
        CONTRACT_SERVICE_USE_SSL: ${CONTRACT_SERVICE_USE_SSL:?CONTRACT_SERVICE_USE_SSL is not set}
        CONTRACT_SERVICE_BUCKET_NAME: ${CONTRACT_SERVICE_BUCKET_NAME:?CONTRACT_SERVICE_BUCKET_NAME is not set}
        CONTRACT_SERVICE_APP_PORT: ${CONTRACT_SERVICE_APP_PORT:?CONTRACT_SERVICE_APP_PORT is not set}
        CONTRACT_SERVICE_SWAGGER_USER: ${CONTRACT_SERVICE_SWAGGER_USER:?CONTRACT_SERVICE_SWAGGER_USER is not set}
        CONTRACT_SERVICE_SWAGGER_PASSWORD: ${CONTRACT_SERVICE_SWAGGER_PASSWORD:?CONTRACT_SERVICE_SWAGGER_PASSWORD is not set}
        CONTRACT_SERVICE_AUTH_EMAIL: ${CONTRACT_SERVICE_AUTH_EMAIL:?CONTRACT_SERVICE_AUTH_EMAIL is not set}
        CONTRACT_SERVICE_AUTH_PASSWORD: ${CONTRACT_SERVICE_AUTH_PASSWORD:?CONTRACT_SERVICE_AUTH_PASSWORD is not set}
        CONTRACT_SERVICE_KEYCLOAK_HOST_URL: ${CONTRACT_SERVICE_KEYCLOAK_HOST_URL:?CONTRACT_SERVICE_KEYCLOAK_HOST_URL is not set}
        CONTRACT_SERVICE_KEYCLOAK_REALM: ${CONTRACT_SERVICE_KEYCLOAK_REALM:?CONTRACT_SERVICE_KEYCLOAK_REALM is not set}
        CONTRACT_SERVICE_KEYCLOAK_CLIENT_ID: ${CONTRACT_SERVICE_KEYCLOAK_CLIENT_ID:?CONTRACT_SERVICE_KEYCLOAK_CLIENT_ID is not set}
        CONTRACT_SERVICE_KEYCLOAK_CLIENT_SECRET: ${CONTRACT_SERVICE_KEYCLOAK_CLIENT_SECRET:?CONTRACT_SERVICE_KEYCLOAK_CLIENT_SECRET is not set}