services:
  epic_global_contracts:
      image: ghcr.io/${org}/epic-global-contracts:${EPIC_GLOBAL_CONTRACTS_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      environment:
        GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY:?GOOGLE_AI_API_KEY is not set}
        OPEN_AI_API_KEY: ${OPEN_AI_API_KEY:?OPEN_AI_API_KEY is not set}
        GOOGLE_API_KEY: ${GOOGLE_API_KEY:?GOOGLE_API_KEY is not set}
        CELERY_BROKER_URL: ${CELERY_BROKER_URL:?CELERY_BROKER_URL is not set}
        CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:?CELERY_RESULT_BACKEND is not set}
        BACKEND_BASE_URL: ${BACKEND_BASE_URL:?BACKEND_BASE_URL is not set}
        AI_BASE_URL: ${AI_BASE_URL:?AI_BASE_URL is not set}
        DATABASE_URI: ${DATABASE_URI:?DATABASE_URI is not set}
        MINIO_ENDPOINT: ${MINIO_ENDPOINT:?MINIO_ENDPOINT is not set}
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:?MINIO_ACCESS_KEY is not set}
        MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:?MINIO_SECRET_KEY is not set}
        MINIO_ROOT_USER: ${MINIO_ROOT_USER:?MINIO_ROOT_USER is not set}
        MINIO_USE_SSL: ${MINIO_USE_SSL:?MINIO_USE_SSL is not set}
        MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:?MINIO_BUCKET_NAME is not set}
        CONTRACT_APP_PORT: ${CONTRACT_APP_PORT:?CONTRACT_APP_PORT is not set}
        PRODUCT_REGISTRY_URL: ${PRODUCT_REGISTRY_URL:?PRODUCT_REGISTRY_URL is not set}
        CONTRACT_SERVICE_SWAGGER_USER: ${AI_SERVICE_SWAGGER_USER:?AI_SERVICE_SWAGGER_USER is not set}
        CONTRACT_SERVICE_SWAGGER_PASSWORD: ${AI_SERVICE_SWAGGER_PASSWORD:?AI_SERVICE_SWAGGER_PASSWORD is not set}