services:
  image_service:
      restart: always
      build:
        context: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/esmagico/image-service.git#${IMAGE_SERVICE_GITHUB_BRANCH:-${DEFAULT_GITHUB_BRANCH:?DEFAULT_GITHUB_BRANCH is not set}}
      environment:
        IMAGE_SERVICE_BUCKET_NAME: ${IMAGE_SERVICE_BUCKET_NAME:?IMAGE_SERVICE_BUCKET_NAME is not set}
        IMAGE_SERVICE_MINIO_ENDPOINT: ${IMAGE_SERVICE_MINIO_ENDPOINT:?IMAGE_SERVICE_MINIO_ENDPOINT is not set}
        IMAGE_SERVICE_MINIO_ACCESS_KEY: ${IMAGE_SERVICE_MINIO_ACCESS_KEY:?IMAGE_SERVICE_MINIO_ACCESS_KEY is not set}
        IMAGE_SERVICE_MINIO_SECRET_KEY: ${IMAGE_SERVICE_MINIO_SECRET_KEY:?IMAGE_SERVICE_MINIO_SECRET_KEY is not set}
        IMAGE_SERVICE_USE_SSL: ${IMAGE_SERVICE_USE_SSL:?IMAGE_SERVICE_USE_SSL is not set} 
        IMAGE_SERVICE_GEMINI_KEY: ${IMAGE_SERVICE_GEMINI_KEY:?IMAGE_SERVICE_GEMINI_KEY is not set}
