include:
  - ./common/monitoring/prod/docker-compose.agents.yaml
  - ./epic/epic_main_website/docker-compose.yaml

services:
  caddy:
    extends:
      file: ./common/caddy/docker-compose.yaml
      service: caddy
    volumes:
      - ./caddyfile-overrides/prod/Caddyfile.prod-mainwebsite:/etc/caddy/Caddyfile
volumes:
  caddy_data:
  caddy_config: