include:
  - ./epic_global_backend/docker-compose.yaml
  - ./epic_global_ai/docker-compose.yaml
  - ./epic_global_frontend/docker-compose.yaml
  - ./epic_global_contracts/docker-compose.yaml
  - ./context_service/docker-compose.yaml