services:
  redis_backend:
    image: redis:latest
    user: "1001"
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis_backend:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./certs:/usr/local/etc/redis/certs:ro
      - ./certs/redis.crt:/usr/local/etc/redis/certs/redis.crt:ro  # Redis server certificate
      - ./certs/redis.key:/usr/local/etc/redis/certs/redis.key  # Redis private key
      - ./certs/ca.crt:/usr/local/etc/redis/certs/ca.crt:ro        # CA public certificate
    ports:
      - "6379:6379" 
    
  redis_ai:
    image: redis:latest
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis_ai:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./certs:/usr/local/etc/redis/certs:ro
      - ./certs/redis.crt:/usr/local/etc/redis/certs/redis.crt:ro  # Redis server certificate
      - ./certs/redis.key:/usr/local/etc/redis/certs/redis.key  # Redis private key
      - ./certs/ca.crt:/usr/local/etc/redis/certs/ca.crt:ro        # CA public certificate
    ports:
      - "6380:6379" 

volumes:
  redis_backend:
  redis_ai: